---
- hosts: proxmox_node
  vars:
    # Proxmox API Credentials (Use Ansible Vault for these in production!)
    haos_proxmox_api_user: "root@pam"
    haos_proxmox_api_password: ${PROXMOX_PW}
    
    # VM Customization for your E8400
    haos_proxmox_node: "optiplex"
    haos_proxmox_vm_id: 100
    haos_proxmox_name: "Home-Assistant-OS"
    haos_proxmox_memory: 2048
    haos_proxmox_cores: 1 # Essential for your dual-core CPU
    haos_proxmox_storage: "local-lvm" # Change to your storage name
    haos_proxmox_onboot: true

  roles:
    - role: nununo.proxmox_haos_install
