---
- hosts: proxmox_nodes
  become: yes  # This tells Ansible to use sudo
  # This tells Ansible to use the new collection for any roles called
  collections:
    - community.proxmox
  
  vars:
    # Use Jinja2 to pull your environment variable
    haos_proxmox_api_user: "chops@pam"
    haos_proxmox_api_password: "{{ lookup('env', 'PROXMOX_PW_CHOPS') }}"

    # We use '| length > 0' to ensure Ansible treats the existence of the string as a Boolean True
    haos_proxmox_mac_address: "84:2B:2B:BE:59:1F"
    # We override the internal variable the role uses to bypass its broken logic check
    haos_net0: "virtio={{ haos_proxmox_mac_address }},bridge=vmbr0"

    # VM Customization for your E8400
    haos_proxmox_node: "optiplex"
    haos_proxmox_vm_id: 100
    haos_proxmox_name: "Home-Assistant-OS"
    haos_proxmox_memory: 2048
    haos_proxmox_cores: 1 
    haos_proxmox_storage: "local-lvm" 
    haos_proxmox_onboot: true

  roles:
    - role: nununo.proxmox_haos_install