# /mnt/usb-data/services/homepage/services.yaml
- Management:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.88.99:3001
        description: Infrastructure Monitoring
        server: my-docker
        container: uptime-kuma
    - Beszel:
        icon: beszel.png
        href: http://192.168.88.99:8090
        description: Resource Stats
        server: my-docker
        container: uptime-kuma
