[proxmox_nodes]
# phenom-a ansible_host=192.168.88.201 # Your Management IP for the host
# phenom-b ansible_host=192.168.88.202 # Your Management IP for the host
optiplex ansible_host=192.168.88.203 ansible_user=root

[apps_vms]
hass-io ansible_host=192.168.88.10
docker-media ansible_host=192.168.88.11

[infra_vms]
adguard-primary ansible_host=192.168.88.5
mqtt-broker ansible_host=192.168.88.6

[storage_vms]
docker-host ansible_host=192.168.88.10
